import { initTheme } from './theme';
import './style.css';
import { normalizeEditorLocale, type XlsxEditorElement } from 'xlsx-web-component';
import type { EditorHandle } from '../../packages/bindings/src/index';
import { mountFramework } from './framework';

const get = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const params = new URLSearchParams(location.search);
initTheme();

const framework = params.get('framework') || import.meta.env.VITE_DEMO_FRAMEWORK || 'vanilla';
get('build-stamp').textContent = `xlsx-viewer demo · ${framework}`;

let toastTimer: ReturnType<typeof setTimeout> | undefined;
function toast(message: string) {
	const element = get('toast');
	element.textContent = message;
	element.hidden = false;
	clearTimeout(toastTimer);
	toastTimer = setTimeout(() => (element.hidden = true), 6000);
}

/** Interface language: `?locale=de` (any supported tag), switchable from the picker. */
const localeSelect = get<HTMLSelectElement>('locale-select');
let locale = normalizeEditorLocale(params.get('locale') ?? undefined);
localeSelect.value = locale;
localeSelect.addEventListener('change', () => {
	locale = normalizeEditorLocale(localeSelect.value);
	const url = new URL(location.href);
	url.searchParams.set('locale', locale);
	history.replaceState(null, '', url);
	for (const element of document.querySelectorAll<XlsxEditorElement>('xlsx-editor'))
		element.locale = locale;
});

let editor: Promise<EditorHandle> | undefined;
function showEditor(): Promise<EditorHandle> {
	get('landing').hidden = true;
	get('workspace').hidden = false;
	editor ??= mountFramework(get('editor'), {
		locale,
		onWorkbookError(error) {
			toast(error.message);
		},
		// What the binding reports back, so the browser tests can check every adapter's events.
		onSelectionChange(detail) {
			get('build-stamp').dataset.selection = detail.ref;
		},
		onDirtyChange(dirty) {
			get('build-stamp').dataset.dirty = String(dirty);
		},
	});
	return editor;
}

function showLandingError(error: unknown) {
	get('workspace').hidden = true;
	get('landing').hidden = false;
	const message = get('landing-error');
	message.textContent = error instanceof Error ? error.message : String(error);
	message.hidden = false;
}

async function openBytes(bytes: Uint8Array, fileName: string) {
	try {
		const handle = await showEditor();
		await handle.load(bytes, fileName);
		handle.element.fileName = fileName;
		handle.element.focusGrid();
	} catch (error) {
		showLandingError(error);
	}
}

async function openFile(file: File) {
	await openBytes(new Uint8Array(await file.arrayBuffer()), file.name);
}

async function openNew() {
	const handle = await showEditor();
	handle.newWorkbook();
	handle.element.fileName = 'Book1.xlsx';
	handle.element.focusGrid();
}

/** The sample is a real file (generated by scripts/sample-workbook.py), not a model built in code. */
async function openSample() {
	try {
		const response = await fetch(`${import.meta.env.BASE_URL}sample.xlsx`);
		if (!response.ok)
			throw new Error(`Could not load the sample workbook (HTTP ${response.status})`);
		await openBytes(new Uint8Array(await response.arrayBuffer()), 'Sample workbook.xlsx');
	} catch (error) {
		showLandingError(error);
	}
}

const landingFile = get<HTMLInputElement>('landing-file');
landingFile.addEventListener('change', () => {
	const file = landingFile.files?.[0];
	landingFile.value = '';
	if (file) void openFile(file);
});
get('browse').addEventListener('click', (event) => {
	event.stopPropagation();
	landingFile.click();
});
get('blank').addEventListener('click', (event) => {
	event.stopPropagation();
	void openNew();
});
get('sample').addEventListener('click', (event) => {
	event.stopPropagation();
	void openSample();
});
// `?sample=1` opens the sample workbook immediately (used by the docs site's embedded demo).
if (params.get('sample') === '1') void openSample();

const dropzone = get('dropzone');
dropzone.addEventListener('click', () => landingFile.click());
dropzone.addEventListener('keydown', (event) => {
	if (event.target === dropzone && (event.key === 'Enter' || event.key === ' ')) {
		event.preventDefault();
		landingFile.click();
	}
});
const carriesFiles = (event: DragEvent) => Boolean(event.dataTransfer?.types.includes('Files'));
for (const type of ['dragenter', 'dragover'] as const)
	document.addEventListener(type, (event) => {
		if (!carriesFiles(event)) return;
		event.preventDefault();
		dropzone.classList.add('dragging');
	});
document.addEventListener('dragleave', (event) => {
	if (!event.relatedTarget) dropzone.classList.remove('dragging');
});
document.addEventListener('drop', (event) => {
	if (!carriesFiles(event)) return;
	event.preventDefault();
	dropzone.classList.remove('dragging');
	const file = event.dataTransfer?.files[0];
	if (file) void openFile(file);
});

// Signals that landing actions are wired (used by browser contracts before clicking).
document.documentElement.dataset.demoReady = 'true';
