// Tiny DOM helpers shared by the grid, formula bar, sheet tabs and context menus. Nothing here
// touches the DOM at import time (SSR-safe); every helper takes the owning document.

/** Creates an element with an optional class name and attributes. */
export function h<K extends keyof HTMLElementTagNameMap>(
	doc: Document,
	tag: K,
	className?: string,
	attrs?: Record<string, string>,
): HTMLElementTagNameMap[K] {
	const node = doc.createElement(tag);
	if (className) node.className = className;
	if (attrs) for (const [name, value] of Object.entries(attrs)) node.setAttribute(name, value);
	return node;
}

/** Sets a style property only when it changed (cheap repaint of recycled nodes). */
export function setStyle(node: HTMLElement, name: string, value: string): void {
	if (node.style.getPropertyValue(name) !== value) node.style.setProperty(name, value);
}

/** Sets pixel geometry in one go. */
export function place(
	node: HTMLElement,
	left: number,
	top: number,
	width: number,
	height: number,
): void {
	node.style.left = `${left}px`;
	node.style.top = `${top}px`;
	node.style.width = `${Math.max(0, width)}px`;
	node.style.height = `${Math.max(0, height)}px`;
}

/** Toggles a class without touching the DOM when nothing changes. */
export function toggleClass(node: Element, name: string, on: boolean): void {
	if (node.classList.contains(name) !== on) node.classList.toggle(name, on);
}

/** Parses SVG markup generated by this package or the core (chart and icon painters, which escape text). */
export function svgNode(doc: Document, markup: string): Element {
	const holder = doc.createElement('div');
	holder.innerHTML = markup;
	return holder.firstElementChild ?? doc.createElement('span');
}

/** The window a node lives in (falls back to the global one). */
export const viewOf = (node: Node): (Window & typeof globalThis) | null =>
	(node.ownerDocument?.defaultView as (Window & typeof globalThis) | null) ??
	(typeof window === 'undefined' ? null : window);

/** requestAnimationFrame with a timer fallback (jsdom, background tabs). */
export function nextFrame(node: Node, fn: () => void): () => void {
	const win = viewOf(node);
	if (win?.requestAnimationFrame) {
		const id = win.requestAnimationFrame(() => fn());
		return () => win.cancelAnimationFrame(id);
	}
	const id = setTimeout(fn, 16);
	return () => clearTimeout(id);
}

/**
 * Adds a `<style data-xg-style="id">` to the shadow root once. Each UI module (grid, formula bar,
 * sheet tabs, menus) ships its own CSS this way, using the `--xve-*` theme tokens.
 */
export function ensureStyle(root: ShadowRoot | HTMLElement, id: string, css: string): void {
	if (root.querySelector(`style[data-xg-style="${id}"]`)) return;
	const doc = root.ownerDocument ?? document;
	const style = doc.createElement('style');
	style.dataset.xgStyle = id;
	style.textContent = css;
	root.append(style);
}
